version: '3.8'

services:
  pricing-api:
    image: ghcr.io/JuliDir/ecommerce_delivery_node:latest
    ports:
      - "3023:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/delivery_db
      - SECURITY_URL=http://localhost:3000
      - CURRENT_USER=/v1/users/current
      - RABBIT_URL=amqp://@localhost:5672
      - QUEUE_ORDERS_REQUEST=order_request_queue
      - QUEUE_DELIVERY_NOTIFICATIONS=delivery_notification_queue
    depends_on:
      - mongo
    networks:
      - pricing-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - delivery-network

volumes:
  mongo-data:

networks:
  delivery-network:
